In [44]:
# 텐서 : 일관된 유형(dtype)을 가진 다차원 배열로 np.arrays와 유사
# 모든 dtypes은 tf.dtypes.DType에서 확인 가능
# 모든 텐서는 Python 숫자 및 문자열과 같이 변경할 수 없음
import tensorflow as tf
import numpy as np

# 기초
# An int32 tensor by defalut
# rank_0_tensor = tf.constant(4)                              # 스칼라(순위-0 텐서) : 단일 값 포함, 축 없음
# print(rank_0_tensor)

# A float tensor
# rank_1_tensor = tf.constant([2.0, 3.0, 4.0])                # 벡터(순위-1 텐서) : 값 목록, 하나의 축
# print(rank_1_tensor)

# If you want to be specific, you can set the dtype at creation time
# rank_2_tensor = tf.constant([[1, 2],
#                              [3, 4],
#                              [5, 6]], dtype=tf.float16)     # 행렬(순위-2 텐서) : 두 개의 축
# print(rank_2_tensor)

# There can be an arbitrary number of axes(somtimes called dimensions)
# rank_3_tensor = tf.constant([
#     [[0, 1, 2, 3, 4],
#      [5, 6, 7, 8, 9]],
#     [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]],
#     [[20, 21, 22, 23, 24],
#      [25, 26, 27, 28, 29]],])                               # 세 개의 축이 있는 텐서
# print(rank_3_tensor)

# np.array 또는 tensor.numpy 메서드를 사용해 텐서를 NumPy 배열로 변환
# np.array(rank_2_tensor)
# rank_2_tensor.numpy()

# 덧셈, 요소별 곱셈 및 행렬 곱셈을 포함한 텐서에 대한 기본 산술 연산 수행 가능
# a = tf.constant([[1, 2],
#                  [3, 4]])
# b = tf.constant([[1, 1],
#                  [1, 1]])                                   # tf.ones([2, 2])

# print(tf.add(a, b))
# print(tf.multiply(a, b))
# print(tf.matmul(a, b))

# print(a + b)                                                # element-wise addition
# print(a * b)                                                # element-wise multiplication
# print(a @ b)                                                # matrix multiplication

# c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# print(tf.reduce_max(c))                                     # Find the largest value
# print(tf.math.argmax(c))                                    # Find the index of the largest value
# print(tf.nn.softmax(c))                                     # Compute the softmax

# tf.convert_to_tensor([1, 2, 3])
# tf.reduce_max([1, 2, 3])
# tf.reduce_max(np.array([1, 2, 3]))


# 형상 정보
# 형상 : 텐서의 각 차원의 길이(요소의 수)
# 순위 : 텐서 축의 수 (스칼라 : 0, 벡터 : 1, 행렬 : 2)
# 축 또는 차원 : 텐서의 특정 차원
# 크기 : 텐서의 총 항목 수, 형상 벡터 요소의 곱
# rank_4_tensor = tf.zeros([3, 2, 4, 5])

# print("Type of every element:", rank_4_tensor.dtype)
# print("Number of axes:", rank_4_tensor.ndim)
# print("Shape of tensor:", rank_4_tensor.shape)
# print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
# print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
# print("Total number of elements (3 * 2 * 4 * 5):", tf.size(rank_4_tensor).numpy())

# Tensor.ndim 및 Tensor.shape 속성은 Tensor 객체를 반환하지 않음
# 따라서, Tensor가 필요한 경우 tf.rank 또는 tf.shape 함수를 사용
# tf.rank(rank_4_tensor)
# tf.shape(rank_4_tensor)


# 인덱싱
## 단일 축 인덱싱
# rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
# print(rank_1_tensor.numpy())

# print("First:", rank_1_tensor[0].numpy())
# print("Second:", rank_1_tensor[1].numpy())
# print("Last:", rank_1_tensor[-1].numpy())

# print("Everything:", rank_1_tensor[:].numpy())
# print("Before 4:", rank_1_tensor[:4].numpy())
# print("From 4 to the end:", rank_1_tensor[4:].numpy())
# print("From 2, before 7:", rank_1_tensor[2:7].numpy())
# print("Every other item:", rank_1_tensor[::2].numpy())
# print("Reversed:", rank_1_tensor[::-1].numpy())

## 다축 인덱싱
# rank_2_tensor = tf.constant([[1, 2],
#                              [3, 4],
#                              [5, 6]], dtype=tf.float16)
# print(rank_2_tensor.numpy())

# Pull out a single value from a 2-rank tensor
# print(rank_2_tensor[1, 1].numpy())

# Get row and column tensors
# print("Second row:", rank_2_tensor[1, :].numpy())
# print("Second column:", rank_2_tensor[:, 1].numpy())
# print("Last row:", rank_2_tensor[-1, :].numpy())
# print("First item in last column:", rank_2_tensor[0, -1].numpy())
# print("Skip the first row:\n", rank_2_tensor[1:, :].numpy())


# 형상 조작
# Shape returns a 'TensorShape' object that shows the size along each axis
# x = tf.constant([[1], [2], [3]])
# print(x.shape)

# You can convert this object into a Python list
# print(x.shape.as_list())

# You can reshape a tensor to a new shape
# Note that you're passing in a list
# reshape = tf.reshape(x, [1, 3])
# print(x.shape)
# print(reshape.shape)

# rank_3_tensor = tf.constant([
#     [[0, 1, 2, 3, 4],
#      [5, 6, 7, 8, 9]],
#     [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]],
#     [[20, 21, 22, 23, 24],
#      [25, 26, 27, 28, 29]],])

# A '-1' passed in the 'shape' argument says "Whatever fits"
# print(tf.reshape(rank_3_tensor, [-1]))

# 일반적으로 tf.reshape의 합리적인 용도는 인접한 축을 결합하거나 분할하는 것뿐임 (또는 1을 추가/제거)
# print(tf.reshape(rank_3_tensor, [3 * 2, 5]))
# print(tf.reshape(rank_3_tensor, [3, 2 * 5]))

# tf.reshape에서 축 교환이 작동하지 않으면, tf.transpose를 수행
# Bad examples
# You can't reorder axes with reshape
# print(tf.reshape(rank_3_tensor, [2, 3, 5]))

# This is a mess
# print(tf.reshape(rank_3_tensor, [5, 6]))

# This doesn't work at all
# try:
#     tf.reshape(rank_3_tensor, [7, -1])
# except Exception as e:
#     print(f"{type(e).__name__}: {e}")


# DTypes에 대한 추가 정보
# tf.tensor의 데이터 유형은 Tensor.dtype 속성을 사용해 검사
# Python 객체에서 tf.Tensor를 만들 때 선택적으로 데이터 유형 지정 가능
# the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
# the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)

# Now, cast to an uint8 and lose the decimal precision
# the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
# print(the_u8_tensor)


# 브로드캐스팅 : 특정 조건에서 작은 텐서는 결합된 연산을 실행할 때 더 큰 텐서에 맞게 자동으로 확장
# x = tf.constant([1, 2, 3])
# y = tf.constant(2)
# z = tf.constant([2, 2, 2])

# All of these are the same computation
# print(tf.multiply(x, 2))
# print(x * y)
# print(x * z)

# These are the same computations
# x = tf.reshape(x, [3, 1])
# y = tf.range(1, 5)

# print(x)
# print(y)
# print(tf.multiply(x, y))

# x_stretch = tf.constant([[1, 1, 1, 1],
#                          [2, 2, 2, 2],
#                          [3, 3, 3, 3]])
# y_stretch = tf.constant([[1, 2, 3, 4],
#                          [1, 2, 3, 4],
#                          [1, 2, 3, 4]])
# print(x_stretch * y_stretch)                                # Again, operator overloading

# tf.broadcast_to를 사용해 브로드캐스팅이 어떤 모습인지 확인 가능
# print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))


# tf.convert_to_tensor
# 대부분의 ops는 텐서가 아닌 인수에 대해 convert_to_tensor를 호출
# 변환 레지스트리가 있어 NumPy의 ndarray, TensorShape, Python 목록 및 tf.Variable과 같은 대부분의 객체 클래스는 모두 자동으로 변환


# 비정형(ragged) 텐서 : 어떤 축을 따라 다양한 수의 요소를 가진 텐서
# 비정형 데이터에는 tf.ragged.RaggedTensor를 사용
# ragged_list = [
#     [0, 1, 2, 3],
#     [4, 5],
#     [6, 7, 8],
#     [9]]

# try:
#     tensor = tf.constant(ragged_list)
# except Exception as e:
#     print(f"{type(e).__name__}: {e}")

# ragged_tensor = tf.ragged.constant(ragged_list)
# print(ragged_tensor)
# print(ragged_tensor.shape)


# 문자열 텐서
# tf.string은 dtype이며, 텐서에서 문자열(가변 길이의 바이트 배열)과 같은 데이터를 나타낼 수 있음
# 문자열은 원자성이므로 Python 문자열과 같은 방식으로 인덱싱 할 수 없음
# scalar_string_tensor = tf.constant("Gray wolf")
# print(scalar_string_tensor)

# If you have three string tensors of different lengths, this is OK
# tensor_of_strings = tf.constant(["Gray wolf",
#                                  "Quick brown fox",
#                                  "Lazy dog"])

# Note that the shape is (3,). The string length is not included
# print(tensor_of_strings)

# b 접두사는 tf.string dtype이 유니코드 문자열이 아닌 바이트 문자열임을 나타냄
# 유니코드 문자를 전달하면 UTF-8로 인코딩
# tf.constant("🥳👍")

# You can use split to split a string into a set of tensors
# print(tf.strings.split(scalar_string_tensor, sep=" "))

# 하지만, 문자열 텐서를 분할하면 비정형 텐서로 변함
# 각 문자열이 서로 다른 수의 부분으로 분할될 수 있기 때문
# print(tf.strings.split(tensor_of_strings))

# text = tf.constant("1 10 100")
# print(tf.strings.to_number(tf.strings.split(text, " ")))

# tf.cast를 사용해 문자열 텐서를 숫자로 변환할 수는 없지만, 바이트로 변환한 다음 숫자로 변환 가능
# byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
# byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)

# print("Byte strings:", byte_strings)
# print("Bytes:", byte_ints)

# Or split it up as unicode and then decode it
# unicode_bytes = tf.constant("アヒル 🦆")
# unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
# unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

# print("Unicode bytes:", unicode_bytes)
# print("Unicode chars:", unicode_char_bytes)
# print("Unicode values:", unicode_values)


# 희소 텐서
# TensorFlow는 tf.sparse.SparseTensor 및 관련 연산을 지원해 희소 데이터를 효율적으로 저장
# 희소 텐서는 메모리 효율적인 방식으로 인덱스별로 값을 저장
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor)

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
